language: ruby

rvm:
  - "1.8.7"
  - "1.9.3"

# Does not run OS X tests =(
script: >
  bundle install &&
  bundle exec rake included_scripts:verify_ruby_syntax &&
  bundle exec rake included_scripts:integration_specs
